name: Publish to npm

on:
  push:
    tags:
      - 'v*' # Only run when a tag like v1.0.0 is pushed

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org/'

      - name: Configure npm auth for publish (uses NODE_AUTH_TOKEN)
        if: env.NPM_TOKEN != ''
        run: echo "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}" > ~/.npmrc
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Set up pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build package
        run: pnpm build

      - name: Verify package.json version matches tag
        id: verify_version
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          PKG_VERSION=$(node -e "console.log(require('./package.json').version)")
          echo "tag=$TAG" >> $GITHUB_OUTPUT
          echo "pkg_version=$PKG_VERSION" >> $GITHUB_OUTPUT
          if [ "$TAG" != "v$PKG_VERSION" ]; then
            echo "Tag ($TAG) does not match package.json version (v$PKG_VERSION)" >&2
            exit 1
          fi

      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: pnpm publish --access public